name: Restore plugins

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore server/plugins
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git revert 23a5bb3 --no-edit

      - name: Push restored files
        run: |
          git push origin HEAD:main
